

DEFAULT_PARAM_SETTINGS = {
    "AccumulatedAnnualDemand": ["YEAR", "FUEL", "REGION"],
    "AnnualEmissionLimit": ["REGION", "EMISSION", "YEAR"],
    "AnnualExogenousEmission": ["REGION", "EMISSION", "YEAR"],
    "AvailabilityFactor": ["REGION", "TECHNOLOGY", "YEAR"],
    "CapacityFactor": ["REGION", "TECHNOLOGY", "TIMESLICE", "YEAR"],
    "CapacityOfOneTechnologyUnit": ["REGION", "TECHNOLOGY", "YEAR"],
    "CapacityToActivityUnit": ["REGION", "TECHNOLOGY", ],
    "CapitalCost": ["REGION", "TECHNOLOGY", "YEAR"],
    "CapitalCostStorage": ["REGION", "STORAGE", "YEAR"],
    "Conversionld": ["TIMESLICE", "DAYTYPE", ],
    "Conversionlh": ["TIMESLICE", "DAILYTIMEBRACKET", ],
    "Conversionls": ["TIMESLICE", "SEASON", ],
    "DaysInDayType": ["SEASON", "DAYTYPE", "YEAR"],
    "DaySplit": ["DAILYTIMEBRACKET", "YEAR", ],
    "DepreciationMethod": ["REGION", ],
    "DiscountRateTech": ["REGION", "TECHNOLOGY", "YEAR"],
    "DiscountRateSto": ["REGION", "STORAGE", "YEAR"],
    "EmissionActivityRatio": ["REGION", "TECHNOLOGY", "EMISSION", "MODE_OF_OPERATION", "YEAR"],
    "EmissionsPenalty": ["REGION", "EMISSION", "YEAR"],
    "FixedCost": ["REGION", "TECHNOLOGY", "YEAR"],
    "InputActivityRatio": ["REGION", "TECHNOLOGY", "FUEL", "MODE_OF_OPERATION", "YEAR"],
    "MinStorageCharge": ["REGION", "STORAGE", "YEAR"],
    "ModelPeriodEmissionLimit": ["REGION", "EMISSION", ],
    "ModelPeriodExogenousEmission": ["REGION", "EMISSION", ],
    "OperationalLife": ["REGION", "TECHNOLOGY", ],
    "OperationalLifeStorage": ["REGION", "STORAGE", ],
    "OutputActivityRatio": ["REGION", "TECHNOLOGY", "FUEL", "MODE_OF_OPERATION", "YEAR"],
    "OutputModeofoperation": ["REGION", "TECHNOLOGY", "MODE_OF_OPERATION", "YEAR"],
    "REMinProductionTarget": ["REGION", "YEAR", ],
    "ReserveMargin": ["REGION", "YEAR", ],
    "ReserveMarginTagFuel": ["REGION", "FUEL", "YEAR"],
    "ReserveMarginTagTechnology": ["REGION", "TECHNOLOGY", "YEAR"],
    "ResidualCapacity": ["REGION", "TECHNOLOGY", "YEAR"],
    "ResidualStorageCapacity": ["REGION", "STORAGE", "YEAR"],
    "RETagFuel": ["REGION", "FUEL", "YEAR"],
    "RETagTechnology": ["REGION", "TECHNOLOGY", "YEAR"],
    "SpecifiedAnnualDemand": ["REGION", "FUEL", "YEAR"],
    "SpecifiedDemandProfile": ["REGION", "FUEL", "TIMESLICE", "YEAR"],
    "StorageMaxCapacity": ["REGION", "STORAGE", ],
    "StorageMaxChargeRate": ["REGION", "STORAGE", ],
    "StorageMaxDischargeRate": ["REGION", "STORAGE", ],
    "StorageLevelStart": ["REGION", "STORAGE", ],
    "StorageUvalue": ["REGION", "STORAGE", "YEAR"],
    "StorageFlowTemperature": ["REGION", "STORAGE", "YEAR"],
    "StorageReturnTemperature": ["REGION", "STORAGE", "YEAR"],
    "StorageAmbientTemperature": ["REGION", "STORAGE", "YEAR"],
    "StorageL2D": ["REGION", "STORAGE", "YEAR"],
    "Storagetagheating": ["REGION", "STORAGE", ],
    "Storagetagcooling": ["REGION", "STORAGE", ],
    "TechnologyFromStorage": ["REGION", "TECHNOLOGY", "STORAGE", "MODE_OF_OPERATION"],
    "TechnologyToStorage": ["REGION", "TECHNOLOGY", "STORAGE", "MODE_OF_OPERATION"],
    "TechWithCapacityNeededToMeetPeakTS": ["REGION", "TECHNOLOGY", ],
    "TotalAnnualMaxCapacity": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalAnnualMaxCapacityInvestment": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalAnnualMinCapacity": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalAnnualMinCapacityInvestment": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalTechnologyAnnualActivityLowerLimit": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalTechnologyAnnualActivityUpperLimit": ["REGION", "TECHNOLOGY", "YEAR"],
    "TotalTechnologyModelPeriodActivityLowerLimit": ["REGION", "TECHNOLOGY", ],
    "TotalTechnologyModelPeriodActivityUpperLimit": ["REGION", "TECHNOLOGY", ],
    "TradeRoute": ["REGION", "REGION2", "FUEL", "YEAR"],
    "VariableCost": ["REGION", "TECHNOLOGY", "MODE_OF_OPERATION", "YEAR"],
    "YearSplit": ["TIMESLICE", "YEAR"]
}
