DEFAULT_PARAM_SETTINGS = {
    "YearSplit": ["YEAR", "TIMESLICE"],
    "AccumulatedAnnualDemand": ["YEAR", "FUEL", "REGION"],
    "AnnualEmissionLimit": ["YEAR", "EMISSION", "REGION" ],
    "AnnualExogenousEmission": ["YEAR", "EMISSION", "REGION"],
    "AvailabilityFactor": ["YEAR", "TECHNOLOGY","REGION"],
    "CapacityFactor": ["YEAR", "TIMESLICE", "TECHNOLOGY", "REGION"],
    "CapacityOfOneTechnologyUnit": ["YEAR", "TECHNOLOGY", "REGION"],
    "CapacityToActivityUnit": ["REGION", "TECHNOLOGY",],
    "CapitalCost": ["YEAR","TECHNOLOGY", "REGION"],
    "CapitalCostStorage": ["YEAR", "STORAGE", "REGION"],
    "Conversionld": ["TIMESLICE", "DAYTYPE", ],
    "Conversionlh": ["TIMESLICE", "DAILYTIMEBRACKET", ],
    "Conversionls": ["TIMESLICE", "SEASON", ],
    "DaysInDayType": ["SEASON", "DAYTYPE", "YEAR"],
    "DaySplit": ["DAILYTIMEBRACKET", "YEAR", ],
    "DepreciationMethod": ["REGION", ],
    "DiscountRateTech": ["YEAR", "TECHNOLOGY", "REGION"],
    "DiscountRateSto": ["YEAR", "STORAGE", "REGION"],
    "EmissionActivityRatio": ["YEAR", "TECHNOLOGY", "MODE_OF_OPERATION", "EMISSION", "REGION"],
    "EmissionsPenalty": ["YEAR", "EMISSION", "REGION"],
    "FixedCost": ["YEAR", "TECHNOLOGY", "REGION"],
    "InputActivityRatio": ["YEAR", "TECHNOLOGY", "MODE_OF_OPERATION", "FUEL", "REGION"],
    "MinStorageCharge": ["YEAR", "STORAGE", "REGION"],
    "ModelPeriodEmissionLimit": ["REGION", "EMISSION", ],
    "ModelPeriodExogenousEmission": ["REGION", "EMISSION", ],
    "OperationalLife": ["REGION", "TECHNOLOGY", ],
    "OperationalLifeStorage": ["REGION", "STORAGE", ],
    "OutputActivityRatio": ["YEAR", "TECHNOLOGY", "MODE_OF_OPERATION", "FUEL", "REGION"],
    "OutputModeofoperation": ["YEAR", "TECHNOLOGY", "MODE_OF_OPERATION", "REGION"],
    "REMinProductionTarget": ["REGION", "YEAR", ],
    "ReserveMargin": ["REGION", "YEAR", ],
    "ReserveMarginTagFuel": ["YEAR", "FUEL", "REGION"],
    "ReserveMarginTagTechnology": ["YEAR", "TECHNOLOGY", "REGION"],
    "ResidualCapacity": ["YEAR", "TECHNOLOGY", "REGION"],
    "ResidualStorageCapacity": ["YEAR", "STORAGE", "REGION"],
    "RETagFuel": ["YEAR", "FUEL", "REGION"],
    "RETagTechnology": ["YEAR", "TECHNOLOGY", "REGION"],
    "SpecifiedAnnualDemand": ["YEAR", "FUEL", "REGION"],
    "SpecifiedDemandProfile": ["YEAR", "TIMESLICE", "FUEL", "REGION"],
    "StorageMaxCapacity": ["REGION", "STORAGE", ],
    "StorageMaxChargeRate": ["REGION", "STORAGE", ],
    "StorageMaxDischargeRate": ["REGION", "STORAGE", ],
    "StorageLevelStart": ["REGION", "STORAGE", ],
    "StorageUvalue": ["YEAR", "STORAGE", "REGION"],
    "StorageFlowTemperature": ["YEAR", "STORAGE", "REGION"],
    "StorageReturnTemperature": ["YEAR", "STORAGE", "REGION"],
    "StorageAmbientTemperature": ["YEAR", "STORAGE", "REGION"],
    "StorageL2D": ["YEAR", "STORAGE", "REGION"],
    "Storagetagheating": ["REGION", "STORAGE", ],
    "Storagetagcooling": ["REGION", "STORAGE", ],
    "TechnologyFromStorage": ["TECHNOLOGY", "STORAGE", "MODE_OF_OPERATION", "REGION"],
    "TechnologyToStorage": ["TECHNOLOGY", "STORAGE", "MODE_OF_OPERATION", "REGION"],
    "TechWithCapacityNeededToMeetPeakTS": ["REGION", "TECHNOLOGY", ],
    "TotalAnnualMaxCapacity": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalAnnualMaxCapacityInvestment": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalAnnualMinCapacity": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalAnnualMinCapacityInvestment": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalTechnologyAnnualActivityLowerLimit": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalTechnologyAnnualActivityUpperLimit": ["YEAR", "TECHNOLOGY", "REGION"],
    "TotalTechnologyModelPeriodActivityLowerLimit": ["REGION", "TECHNOLOGY", ],
    "TotalTechnologyModelPeriodActivityUpperLimit": ["REGION", "TECHNOLOGY", ],
    "TradeRoute": ["YEAR", "FUEL", "REGION2", "REGION"],
    "VariableCost": ["YEAR", "TECHNOLOGY", "MODE_OF_OPERATION", "REGION" ],
    "GIS_Losses": ["FUEL", "REGION" ]
}
